version: '2'

services:
  proxy:
    image: traefik
    container_name: traefik
    command: --web --web.address=":8080" --docker --docker.domain="vinnward.net" --docker.usebindportip=true --docker.exposedbydefault=false --docker.endpoint=unix://var/run/docker.sock
    networks:
      - default
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/etc/traefik/traefik.toml

networks:
  default:
    driver: bridge
